name: Checkout pnpm project

description: |
  Checkout a pnpm project and install dependencies with caching

branding:
  icon: arrow-down-circle
  color: blue

author: tobysmith568

inputs:
  package-json:
    description: Path to the package.json file
    required: false
    default: ./package.json
  node-version:
    description: Node.js version
    required: false
    default: "22"
  ref:
    description: The git ref to checkout
    default: ""
    required: false

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        
    - name: Use Latest Corepack
      run: |
        echo "Before: corepack version => $(corepack --version || echo 'not installed')"
        npm install -g corepack@latest
        echo "After : corepack version => $(corepack --version)"
        corepack enable

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: https://registry.npmjs.org

    - name: Set working directory from package.json path
      id: set-working-dir
      shell: pwsh
      run: |
        $dir = Split-Path "${{ inputs.package-json }}"
        echo "working_dir=$dir" >> $env:GITHUB_ENV

    - name: Install dependencies
      run: pnpm install
      shell: pwsh
      working-directory: ${{ env.working_dir }}
